config/routes.rb
Libreconf::Application.routes.draw do

  	
  resources :workshops, path: 'admin/workshops'

  resources :speakers, path: 'admin/speakers'

  devise_for :users

  resources :abstract_statuses, path: 'admin/abstract_statuses'

  resources :sponsor_types, path: 'admin/sponsor_types'

  resources :sponsors, path: 'admin/sponsors'

  resources :abstracts, path: 'admin/abstracts'

  get "home/index"
  
  root :to => 'home#index'

  match 'contact' => 'contact#new', :via => :get
  match 'contact' => 'contact#create', :via => :post
  
  match 'tourism' => 'pages#tourism', :via => :get
  match 'CfP' => 'pages#CfP', :via => :get
  match 'accommodation' => 'pages#accommodation', :via => :get
  match 'hospedaje' => 'pages#accommodation', :via => :get
  match 'transportation' => 'pages#transportation', :via => :get
  match 'transporte' => 'pages#transportation', :via => :get
  match 'press' => 'pages#press', :via => :get
  match 'calendar' => 'pages#calendar', :via => :get
  match 'calendario' => 'pages#calendar', :via => :get
  #ActionDispatch::Routing::Translator.translate_from_file('config/locales/routes.yml')
  
  match 'program' => 'wiki_mirror#program', :via => :get 
  match 'program/:year' => 'wiki_mirror#program', :via => :get
  
  match 'session/*title' => 'wiki_mirror#sessn', :via => :get
end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = Workshop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workshops }
    end
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
    @workshop = Workshop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workshop }
    end
  end

  # GET /workshops/new
  # GET /workshops/new.json
  def new
    @workshop = Workshop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workshop }
    end
  end

  # GET /workshops/1/edit
  def edit
    @workshop = Workshop.find(params[:id])
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(params[:workshop])

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render json: @workshop, status: :created, location: @workshop }
      else
        format.html { render action: "new" }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workshops/1
  # PUT /workshops/1.json
  def update
    @workshop = Workshop.find(params[:id])

    respond_to do |format|
      if @workshop.update_attributes(params[:workshop])
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop = Workshop.find(params[:id])
    @workshop.destroy

    respond_to do |format|
      format.html { redirect_to workshops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
<%= form_for @workshop, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field input-xxlarge' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area input-xxlarge' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :author, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :author, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :capacity, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :capacity, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                workshops_path, :class => 'btn' %>
  </div>
<% end %>

app/views/workshops/edit.html.erb
<%- model_class = Workshop -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/workshops/index.html.erb
<%- model_class = Workshop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human(:count => 2) %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:author) %></th>
      <th><%= model_class.human_attribute_name(:capacity) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @workshops.each do |workshop| %>
      <tr>
        <td><%= link_to workshop.id, workshop_path(workshop) %></td>
        <td><%= workshop.title %></td>
        <td><%= workshop.author %></td>
        <td><%= workshop.capacity %></td>
        <td><%=l workshop.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_workshop_path(workshop), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      workshop_path(workshop),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_workshop_path,
            :class => 'btn btn-primary' %>

app/views/workshops/new.html.erb
<%- model_class = Workshop -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/workshops/show.html.erb
<%- model_class = Workshop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @workshop.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:author) %>:</strong></dt>
  <dd><%= @workshop.author %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @workshop.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:capacity) %>:</strong></dt>
  <dd><%= @workshop.capacity %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              workshops_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_workshop_path(@workshop), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              workshop_path(@workshop),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>