config/routes.rb
Libreconf::Application.routes.draw do

  	
  resources :workshops, path: 'admin/workshops'

  resources :speakers, path: 'admin/speakers'

  devise_for :users

  resources :abstract_statuses, path: 'admin/abstract_statuses'

  resources :sponsor_types, path: 'admin/sponsor_types'

  resources :sponsors, path: 'admin/sponsors'

  resources :abstracts, path: 'admin/abstracts'

  get "home/index"
  
  root :to => 'home#index'

  match 'contact' => 'contact#new', :via => :get
  match 'contact' => 'contact#create', :via => :post
  
  match 'tourism' => 'pages#tourism', :via => :get
  match 'CfP' => 'pages#CfP', :via => :get
  match 'accommodation' => 'pages#accommodation', :via => :get
  match 'hospedaje' => 'pages#accommodation', :via => :get
  match 'transportation' => 'pages#transportation', :via => :get
  match 'transporte' => 'pages#transportation', :via => :get
  match 'press' => 'pages#press', :via => :get
  match 'calendar' => 'pages#calendar', :via => :get
  match 'calendario' => 'pages#calendar', :via => :get
  #ActionDispatch::Routing::Translator.translate_from_file('config/locales/routes.yml')
  
  match 'program' => 'wiki_mirror#program', :via => :get 
  match 'program/:year' => 'wiki_mirror#program', :via => :get
  
  match 'session/*title' => 'wiki_mirror#sessn', :via => :get
end

app/controllers/abstract_statuses_controller.rb
class AbstractStatusesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /abstract_statuses
  # GET /abstract_statuses.json
  def index
    @abstract_statuses = AbstractStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @abstract_statuses }
    end
  end

  # GET /abstract_statuses/1
  # GET /abstract_statuses/1.json
  def show
    @abstract_status = AbstractStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @abstract_status }
    end
  end

  # GET /abstract_statuses/new
  # GET /abstract_statuses/new.json
  def new
    @abstract_status = AbstractStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @abstract_status }
    end
  end

  # GET /abstract_statuses/1/edit
  def edit
    @abstract_status = AbstractStatus.find(params[:id])
  end

  # POST /abstract_statuses
  # POST /abstract_statuses.json
  def create
    @abstract_status = AbstractStatus.new(params[:abstract_status])

    respond_to do |format|
      if @abstract_status.save
        format.html { redirect_to @abstract_status, notice: 'Abstract status was successfully created.' }
        format.json { render json: @abstract_status, status: :created, location: @abstract_status }
      else
        format.html { render action: "new" }
        format.json { render json: @abstract_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /abstract_statuses/1
  # PUT /abstract_statuses/1.json
  def update
    @abstract_status = AbstractStatus.find(params[:id])

    respond_to do |format|
      if @abstract_status.update_attributes(params[:abstract_status])
        format.html { redirect_to @abstract_status, notice: 'Abstract status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @abstract_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abstract_statuses/1
  # DELETE /abstract_statuses/1.json
  def destroy
    @abstract_status = AbstractStatus.find(params[:id])
    @abstract_status.destroy

    respond_to do |format|
      format.html { redirect_to abstract_statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/abstract_statuses_helper.rb
module AbstractStatusesHelper
end

app/views/abstract_statuses/_form.html.erb
<%= form_for @abstract_status, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                abstract_statuses_path, :class => 'btn' %>
  </div>
<% end %>

app/views/abstract_statuses/edit.html.erb
<%- model_class = AbstractStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/abstract_statuses/index.html.erb
<%- model_class = AbstractStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @abstract_statuses.each do |abstract_status| %>
      <tr>
        <td><%= link_to abstract_status.id, abstract_status_path(abstract_status) %></td>
        <td><%= abstract_status.name %></td>
        <td><%=l abstract_status.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_abstract_status_path(abstract_status), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      abstract_status_path(abstract_status),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_abstract_status_path,
            :class => 'btn btn-primary' %>

app/views/abstract_statuses/new.html.erb
<%- model_class = AbstractStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default =>   t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/abstract_statuses/show.html.erb
<%- model_class = AbstractStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @abstract_status.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              abstract_statuses_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_abstract_status_path(@abstract_status), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              abstract_status_path(@abstract_status),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>