config/routes.rb
Libreconf::Application.routes.draw do

  	
  resources :workshops, path: 'admin/workshops'

  resources :speakers, path: 'admin/speakers'

  devise_for :users

  resources :abstract_statuses, path: 'admin/abstract_statuses'

  resources :sponsor_types, path: 'admin/sponsor_types'

  resources :sponsors, path: 'admin/sponsors'

  resources :abstracts, path: 'admin/abstracts'

  get "home/index"
  
  root :to => 'home#index'

  match 'contact' => 'contact#new', :via => :get
  match 'contact' => 'contact#create', :via => :post
  
  match 'tourism' => 'pages#tourism', :via => :get
  match 'CfP' => 'pages#CfP', :via => :get
  match 'accommodation' => 'pages#accommodation', :via => :get
  match 'hospedaje' => 'pages#accommodation', :via => :get
  match 'transportation' => 'pages#transportation', :via => :get
  match 'transporte' => 'pages#transportation', :via => :get
  match 'press' => 'pages#press', :via => :get
  match 'calendar' => 'pages#calendar', :via => :get
  match 'calendario' => 'pages#calendar', :via => :get
  #ActionDispatch::Routing::Translator.translate_from_file('config/locales/routes.yml')
  
  match 'program' => 'wiki_mirror#program', :via => :get 
  match 'program/:year' => 'wiki_mirror#program', :via => :get
  
  match 'session/*title' => 'wiki_mirror#sessn', :via => :get
end

app/models/abstract.rb
class Abstract < ActiveRecord::Base
  belongs_to :abstract_status
  after_create :notify_created
  after_save :notify_approved

  private
    def notify_created
      ApplicationMailer.abstract_created_notification(self).deliver
    end
    
    def notify_approved
      ApplicationMailer.abstract_approved_notification(self).deliver if self.abstract_status_id_changed? and self.abstract_status_id == AbstractStatus::APPROVED
    end
end

app/controllers/abstracts_controller.rb
class AbstractsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_abstract, only: [:show, :edit, :update, :destroy]

  # GET /abstracts
  # GET /abstracts.json
  def index
    if params.has_key?(:abstract_status_id)
      @abstracts = Abstract.where(:abstract_status_id => params[:abstract_status_id])
    else
      @abstracts = Abstract.where("abstract_status_id < ?", AbstractStatus::APPROVED)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @abstracts }
    end
  end

  # GET /abstracts/1
  # GET /abstracts/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @abstract }
    end
  end

  # GET /abstracts/new
  # GET /abstracts/new.json
  def new
    @abstract = Abstract.new

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @abstract }
    end
  end

  # GET /abstracts/1/edit
  def edit
    @abstract = Abstract.find(params[:id])
  end

  # POST /abstracts
  # POST /abstracts.json
  def create
    @abstract = Abstract.new(abstract_params)

    respond_to do |format|
      if (user_signed_in? or verify_recaptcha) and @abstract.save
        if user_signed_in?
          format.html { redirect_to @abstract, notice: t(:abstract_created) }
        else
          format.html { redirect_to root_path, notice: t(:abstract_created) }
        end
        # format.json { render json: @abstract, status: :created, location: @abstract }
      else
        format.html { render action: "new" }
        #format.json { render json: @abstract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /abstracts/1
  # PUT /abstracts/1.json
  def update
    respond_to do |format|
      if @abstract.update_attributes(abstract_params)
        format.html { redirect_to @abstract, notice: 'Abstract was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @abstract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abstracts/1
  # DELETE /abstracts/1.json
  def destroy
    @abstract.destroy

    respond_to do |format|
      format.html { redirect_to abstracts_url, notice: 'Abstract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_abstract
      @abstract = Abstract.find(params[:id])
    end

    def abstract_params
      params.require(:abstract).permit(:author, :email, :country, :organization, :title, :description, :status_id)
    end

end

app/helpers/abstracts_helper.rb
module AbstractsHelper
end

app/views/abstracts/_form.html.erb
<%= form_for @abstract, :html => { :class => 'form-horizontal' } do |f| %>
  <% if user_signed_in? and not @abstract.id.nil? %>
    <div class="control-group">
      <%= f.label t(:status), :class => 'control-label' %>
      <div class="controls">
        <%= collection_select(:abstract, :abstract_status_id, AbstractStatus.all, :id, :name) %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :is_key, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :is_key, :class => 'checkbox' %>
      </div>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :author, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :author, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :organization, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :organization, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field input-xxlarge' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area input-xxlarge' %>
    </div>
  </div>
  <% unless user_signed_in? %>
    <div class="control-group">
      <div class="controls">
        <%= recaptcha_tags %>
      </div>
    </div>
  <% end %>
  
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                abstracts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/abstracts/edit.html.erb
<%- model_class = Abstract -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/abstracts/index.html.erb
<%- model_class = Abstract -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human(:count => 2) %></h1>
</div>
<%= form_tag(:abstracts, :method => "get") do %>
  <% AbstractStatus.order(:id).each do |status| %> 
    <%= check_box_tag 'abstract_status_id[]', status.id, ((params[:abstract_status_id] and params[:abstract_status_id].include?(status.id.to_s)) or (!params[:abstract_status_id] and status.id < AbstractStatus::APPROVED)) %>
    <%= status.name %>
  <% end %>
  <%= submit_tag(t(:filter), :class => 'btn btn-mini btn-primary') %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:is_key) %></th>
      <th><%= t('status') %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:author) %></th>
      <th><%= model_class.human_attribute_name(:organization) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @abstracts.each do |abstract| %>
      <tr>
        <td><%= link_to abstract.id, abstract_path(abstract) %></td>
        <td><i class="<%= abstract.is_key ? 'icon-ok' : 'icon-remove' %>"></i></td>
        <td><%= abstract.abstract_status.name %></td>
        <td><%= abstract.title %></td>
        <td><%= abstract.author %></td>
        <td><%= abstract.organization %></td>
        <td><%= abstract.country %></td>
        <td><%= abstract.email %></td>
        <td><%=l abstract.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_abstract_path(abstract), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      abstract_path(abstract),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_abstract_path,
            :class => 'btn btn-primary' %>

app/views/abstracts/new.html.erb
<%- model_class = Abstract -%>
<div class="page-header">
  <h1><%= t(:new_abstract) %></h1>
</div>
<div class="alert alert-block alert-info">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= t('abstract_disclaimer.html') %>
</div>
<%= render :partial => 'form' %>

app/views/abstracts/show.html.erb
<%- model_class = Abstract -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:is_key) %>:</strong></dt>
  <dd><i class="<%= @abstract.is_key ? 'icon-ok' : 'icon-remove' %>"></i></dd>
  <dt><strong><%= model_class.human_attribute_name(:author) %>:</strong></dt>
  <dd><%= @abstract.author %></dd>
  <dt><strong><%= model_class.human_attribute_name(:organization) %>:</strong></dt>
  <dd><%= @abstract.organization %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @abstract.country %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @abstract.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @abstract.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @abstract.description %></dd>
  <dt><strong><%= t(:status) %>:</strong></dt>
  <dd><%= @abstract.abstract_status.name %></dd>
  
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              abstracts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_abstract_path(@abstract), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              abstract_path(@abstract),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>